version: '3.8'
services:
  backend:
    build: ./backend
    expose:
      - "4000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
